// The content CRUD tool group (Arc 2 §2.3): thin wrappers over src/db/repository.ts,
// exposed to an MCP client behind a one-time write grant per course (§2.4 — a later task
// wires actual grant checking). These are additive or idempotent by construction, so no
// snapshot/undo pairing is needed here (contrast the destructive group, a later task).
//
// `update_card` deliberately accepts only content fields (front/back/tags/flagged) —
// never FSRS/scheduling fields — per src/mcp/registry.ts's documented exclusion. Every
// tool that touches a card also refuses to edit sequence-generated cards (those with a
// `sequenceItemId`), mirroring repository.ts's `assertNoGeneratedCards` convention: such
// cards may only be added, edited or removed via their owning sequence.

import { z } from 'zod';
import { db } from '../../db/schema';
import * as read from '../../db/read';
import {
  createCourse as repoCreateCourse,
  updateCourse as repoUpdateCourse,
  createLesson as repoCreateLesson,
  updateLesson as repoUpdateLesson,
  createNote as repoCreateNote,
  updateNote as repoUpdateNote,
  createCourseCard,
  createLessonCard,
  updateCard as repoUpdateCard,
  linkCardToLesson as repoLinkCardToLesson,
  createSequence as repoCreateSequence,
  updateSequence as repoUpdateSequence,
  createCourseExamDate as repoCreateCourseExamDate,
  updateCourseExamDate as repoUpdateCourseExamDate,
} from '../../db/repository';
import { McpToolException, type ToolDefinition, type ToolResult } from '../types';

const courseIdSchema = z.string().describe('The id of the course.');
const lessonIdSchema = z.string().describe('The id of the lesson.');

function ok<T>(data: T): ToolResult<T> {
  return { data };
}

function notFound(kind: string, id: string): never {
  throw new McpToolException({ kind: 'not_found', message: `${kind} "${id}" was not found.` });
}

function refuseGeneratedCard(cardId: string): never {
  throw new McpToolException({
    kind: 'conflict',
    message:
      `Card "${cardId}" was generated by a sequence and can only be edited via that sequence ` +
      '(lacuna.update_sequence), not directly.',
  });
}

// ---------------------------------------------------------------------------
// Courses
// ---------------------------------------------------------------------------

const createCourseSchema = z.object({
  name: z.string().describe('The course name.'),
  description: z.string().optional().describe('Optional free-text description.'),
});
const createCourse: ToolDefinition<z.infer<typeof createCourseSchema>, Awaited<ReturnType<typeof repoCreateCourse>>> = {
  name: 'lacuna.create_course',
  description: 'Create a new course with sensible scheduling defaults (exam date, FSRS parameters, unlock mode).',
  inputSchema: createCourseSchema,
  requiredScope: 'write',
  async handler({ name, description }) {
    return ok(await repoCreateCourse(name, description !== undefined ? { description } : undefined));
  },
};

const updateCourseSchema = z.object({
  courseId: courseIdSchema,
  name: z.string().optional().describe('New course name.'),
  description: z.string().optional().describe('New free-text description.'),
  examDate: z.number().optional().describe('New primary exam date/time, as an epoch millisecond value in UTC.'),
});
const updateCourse: ToolDefinition<z.infer<typeof updateCourseSchema>, { id: string }> = {
  name: 'lacuna.update_course',
  description: "Update a course's name, description, and/or primary exam date.",
  inputSchema: updateCourseSchema,
  requiredScope: 'write',
  async handler({ courseId, ...changes }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    await repoUpdateCourse(courseId, changes);
    return ok({ id: courseId });
  },
};

// ---------------------------------------------------------------------------
// Lessons
// ---------------------------------------------------------------------------

const createLessonSchema = z.object({
  courseId: courseIdSchema,
  name: z.string().describe('The lesson name.'),
  description: z.string().optional().describe('Optional free-text description.'),
});
const createLesson: ToolDefinition<z.infer<typeof createLessonSchema>, Awaited<ReturnType<typeof repoCreateLesson>>> = {
  name: 'lacuna.create_lesson',
  description: "Create a new lesson at the end of a course's path.",
  inputSchema: createLessonSchema,
  requiredScope: 'write',
  async handler({ courseId, name, description }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    return ok(await repoCreateLesson(courseId, name, description !== undefined ? { description } : undefined));
  },
};

const updateLessonSchema = z.object({
  lessonId: lessonIdSchema,
  name: z.string().optional().describe('New lesson name.'),
  description: z.string().optional().describe('New free-text description.'),
});
const updateLesson: ToolDefinition<z.infer<typeof updateLessonSchema>, { id: string }> = {
  name: 'lacuna.update_lesson',
  description: "Update a lesson's name and/or description.",
  inputSchema: updateLessonSchema,
  requiredScope: 'write',
  async handler({ lessonId, ...changes }) {
    if (!(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
    await repoUpdateLesson(lessonId, changes);
    return ok({ id: lessonId });
  },
};

// ---------------------------------------------------------------------------
// Notes
// ---------------------------------------------------------------------------

const createNoteSchema = z.object({
  lessonId: lessonIdSchema,
  name: z.string().describe('The note name.'),
  content: z.string().optional().describe('Rich Markdown source. Defaults to empty.'),
});
const createNote: ToolDefinition<z.infer<typeof createNoteSchema>, Awaited<ReturnType<typeof repoCreateNote>>> = {
  name: 'lacuna.create_note',
  description: "Create a new Markdown note at the end of a lesson's notes.",
  inputSchema: createNoteSchema,
  requiredScope: 'write',
  async handler({ lessonId, name, content }) {
    if (!(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
    return ok(await repoCreateNote(lessonId, name, content));
  },
};

const updateNoteSchema = z.object({
  noteId: z.string().describe('The id of the note to update.'),
  name: z.string().optional().describe('New note name.'),
  content: z.string().optional().describe('New Markdown source.'),
});
const updateNote: ToolDefinition<z.infer<typeof updateNoteSchema>, { id: string }> = {
  name: 'lacuna.update_note',
  description: "Update a note's name and/or Markdown content.",
  inputSchema: updateNoteSchema,
  requiredScope: 'write',
  async handler({ noteId, ...changes }) {
    if (!(await db.notes.get(noteId))) notFound('Note', noteId);
    await repoUpdateNote(noteId, changes);
    return ok({ id: noteId });
  },
};

// ---------------------------------------------------------------------------
// Cards
// ---------------------------------------------------------------------------

const cardTypeSchema = z.enum(['front_back', 'cloze', 'basic_reversed']).describe('The card type.');

const createCardSchema = z.object({
  courseId: courseIdSchema,
  lessonId: z
    .string()
    .optional()
    .describe('If given, create the card in this lesson. Otherwise create it unassigned, in the course question bank.'),
  type: cardTypeSchema,
  front: z.string().describe('Markdown source for the question/prompt side.'),
  back: z.string().describe("Markdown source for the answer side. Unused (empty) for cloze cards."),
  tags: z.array(z.string()).optional().describe('Free-text tags. Defaults to none.'),
});
const createCard: ToolDefinition<z.infer<typeof createCardSchema>, Awaited<ReturnType<typeof createCourseCard>>> = {
  name: 'lacuna.create_card',
  description:
    "Create a new card, either unassigned in a course's question bank or assigned to a lesson " +
    'when lessonId is given.',
  inputSchema: createCardSchema,
  requiredScope: 'write',
  async handler({ courseId, lessonId, type, front, back, tags }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    if (lessonId !== undefined) {
      if (!(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
      return ok(await createLessonCard(courseId, lessonId, type, front, back, tags));
    }
    return ok(await createCourseCard(courseId, type, front, back, tags));
  },
};

const updateCardSchema = z.object({
  cardId: z.string().describe('The id of the card to update.'),
  front: z.string().optional().describe('New Markdown source for the question/prompt side.'),
  back: z.string().optional().describe('New Markdown source for the answer side.'),
  tags: z.array(z.string()).optional().describe('Replacement set of free-text tags.'),
  flagged: z.boolean().optional().describe('New flagged state, for quick filtering/follow-up.'),
});
const updateCard: ToolDefinition<z.infer<typeof updateCardSchema>, { id: string }> = {
  name: 'lacuna.update_card',
  description:
    "Update a card's content: front, back, tags, and/or flagged state. Never touches FSRS " +
    'scheduling fields (state, stability, difficulty, due) — those are the study engine\'s ' +
    'exclusive write path. Refuses cards generated by a sequence; edit those via lacuna.update_sequence.',
  inputSchema: updateCardSchema,
  requiredScope: 'write',
  async handler({ cardId, ...changes }) {
    const card = await read.getCard(cardId);
    if (!card) notFound('Card', cardId);
    if (card.sequenceItemId !== undefined) refuseGeneratedCard(cardId);
    await repoUpdateCard(cardId, changes);
    return ok({ id: cardId });
  },
};

const linkCardToLessonSchema = z.object({
  lessonId: lessonIdSchema,
  cardId: z.string().describe('The id of the card to link.'),
});
const linkCardToLesson: ToolDefinition<z.infer<typeof linkCardToLessonSchema>, Awaited<ReturnType<typeof repoLinkCardToLesson>>> = {
  name: 'lacuna.link_card_to_lesson',
  description:
    "Display-link an existing card into an additional lesson, alongside its primary lesson. " +
    'Idempotent: linking an already-linked card is a no-op that returns the existing link.',
  inputSchema: linkCardToLessonSchema,
  requiredScope: 'write',
  async handler({ lessonId, cardId }) {
    if (!(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
    if (!(await read.getCard(cardId))) notFound('Card', cardId);
    return ok(await repoLinkCardToLesson(lessonId, cardId));
  },
};

// ---------------------------------------------------------------------------
// Sequences
// ---------------------------------------------------------------------------

const sequenceItemSchema = z.object({
  id: z.string().describe('Stable id for this item — anchors the card(s) generated from it across edits.'),
  value: z.string().describe('Markdown source for the recallable unit.'),
  label: z.string().optional().describe('Optional display key (e.g. "11" for Sodium).'),
  chunkIndex: z.number().int().optional().describe('Membership of a named chunk (see chunkLabels).'),
  speaker: z.string().optional().describe('`lines` mode only: who speaks this line.'),
});

const createSequenceSchema = z.object({
  courseId: courseIdSchema,
  lessonId: z
    .string()
    .optional()
    .describe('If given, scope the sequence (and its generated cards) to this lesson. Otherwise the course question bank.'),
  name: z.string().describe('The sequence name.'),
  items: z.array(sequenceItemSchema).describe('Ordered recallable units the sequence generates cards from.'),
  cueWindow: z.number().int().optional().describe('How many preceding items are shown as cue. Defaults to 2.'),
  mode: z
    .enum(['list', 'lines'])
    .optional()
    .describe('`list` (default): every item generates a positional recall card. `lines`: script mode, see mySpeaker.'),
  mySpeaker: z.string().optional().describe('`lines` mode only: the speaker whose lines are the recall target.'),
});
const createSequence: ToolDefinition<z.infer<typeof createSequenceSchema>, Awaited<ReturnType<typeof repoCreateSequence>>> = {
  name: 'lacuna.create_sequence',
  description:
    'Create a new overlapping-cloze sequence and, in the same transaction, every card it generates.',
  inputSchema: createSequenceSchema,
  requiredScope: 'write',
  async handler({ courseId, lessonId, name, items, cueWindow, mode, mySpeaker }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    if (lessonId !== undefined && !(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
    const opts: Partial<Awaited<ReturnType<typeof repoCreateSequence>>> = {};
    if (cueWindow !== undefined) opts.cueWindow = cueWindow;
    if (mode !== undefined) opts.mode = mode;
    if (mySpeaker !== undefined) opts.mySpeaker = mySpeaker;
    return ok(await repoCreateSequence(courseId, lessonId ?? null, name, items, opts));
  },
};

const updateSequenceSchema = z.object({
  sequenceId: z.string().describe('The id of the sequence to update.'),
  name: z.string().optional().describe('New sequence name.'),
  items: z.array(sequenceItemSchema).optional().describe('Replacement ordered list of recallable units.'),
  cueWindow: z.number().int().optional().describe('New cue window.'),
});
const updateSequence: ToolDefinition<z.infer<typeof updateSequenceSchema>, { id: string }> = {
  name: 'lacuna.update_sequence',
  description:
    "Update a sequence's name, items, and/or cue window, regenerating its cards to match. Card " +
    'content is diffed and updated in place where possible, so existing FSRS memory state ' +
    'survives content-only regeneration.',
  inputSchema: updateSequenceSchema,
  requiredScope: 'write',
  async handler({ sequenceId, name, items, cueWindow }) {
    const existing = await read.getSequence(sequenceId);
    if (!existing) notFound('Sequence', sequenceId);
    await repoUpdateSequence({
      ...existing,
      ...(name !== undefined ? { name } : {}),
      ...(items !== undefined ? { items } : {}),
      ...(cueWindow !== undefined ? { cueWindow } : {}),
    });
    return ok({ id: sequenceId });
  },
};

// ---------------------------------------------------------------------------
// Course exam dates
// ---------------------------------------------------------------------------

const createCourseExamDateSchema = z.object({
  courseId: courseIdSchema,
  name: z.string().describe('e.g. "Mid-term", "Mock exam", "Final".'),
  examDate: z.number().describe('The date/time as an epoch millisecond value, in UTC.'),
  lessonIds: z
    .array(z.string())
    .optional()
    .describe('Lessons whose cards are in scope for this date. Omit for all lessons so far (a checkpoint).'),
});
const createCourseExamDate: ToolDefinition<z.infer<typeof createCourseExamDateSchema>, Awaited<ReturnType<typeof repoCreateCourseExamDate>>> = {
  name: 'lacuna.create_course_exam_date',
  description: 'Add an extra exam date or checkpoint to a course; the scheduler always targets the nearest applicable date.',
  inputSchema: createCourseExamDateSchema,
  requiredScope: 'write',
  async handler({ courseId, name, examDate, lessonIds }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    return ok(
      await repoCreateCourseExamDate(courseId, name, examDate, lessonIds !== undefined ? { lessonIds } : undefined),
    );
  },
};

const updateCourseExamDateSchema = z.object({
  courseExamDateId: z.string().describe('The id of the course exam date to update.'),
  name: z.string().optional().describe('New name.'),
  examDate: z.number().optional().describe('New date/time as an epoch millisecond value, in UTC.'),
  lessonIds: z.array(z.string()).optional().describe('New lesson scope.'),
});
const updateCourseExamDate: ToolDefinition<z.infer<typeof updateCourseExamDateSchema>, { id: string }> = {
  name: 'lacuna.update_course_exam_date',
  description: "Update a course exam date/checkpoint's name, date, and/or lesson scope.",
  inputSchema: updateCourseExamDateSchema,
  requiredScope: 'write',
  async handler({ courseExamDateId, ...changes }) {
    if (!(await db.courseExamDates.get(courseExamDateId))) notFound('Course exam date', courseExamDateId);
    await repoUpdateCourseExamDate(courseExamDateId, changes);
    return ok({ id: courseExamDateId });
  },
};

/** The content CRUD tool group, in the order they appear in Arc 2 §2.3's inventory. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- a heterogeneous tool list is necessarily ToolDefinition<any, any>; each entry above is still checked against its own concrete Input/Output.
export const CONTENT_TOOLS: readonly ToolDefinition<any, any>[] = [
  createCourse,
  updateCourse,
  createLesson,
  updateLesson,
  createNote,
  updateNote,
  createCard,
  updateCard,
  linkCardToLesson,
  createSequence,
  updateSequence,
  createCourseExamDate,
  updateCourseExamDate,
];

// Also export individually for direct handler-level unit tests.
export {
  createCourse,
  updateCourse,
  createLesson,
  updateLesson,
  createNote,
  updateNote,
  createCard,
  updateCard,
  linkCardToLesson,
  createSequence,
  updateSequence,
  createCourseExamDate,
  updateCourseExamDate,
};
