// The content CRUD tool group (Arc 2 §2.3): thin wrappers over src/db/repository.ts,
// exposed to an MCP client behind a one-time write grant per course (§2.4 — a later task
// wires actual grant checking). These are additive or idempotent by construction, so no
// snapshot/undo pairing is needed here (contrast the destructive group, a later task).
//
// `update_card` deliberately accepts only content fields (front/back/tags/flagged) —
// never FSRS/scheduling fields — per src/mcp/registry.ts's documented exclusion. Every
// tool that touches a card also refuses to edit generated cards (those with a
// `sequenceItemId` or an `occlusionRegionId`), mirroring repository.ts's
// `assertNoGeneratedCards` convention: such cards may only be added, edited or removed via
// their owning sequence or occlusion.

import type { z } from 'zod';
import { db } from '../../db/schema';
import type { CourseAssessment } from '../../db/types';
import * as read from '../../db/read';
import {
  createCourse as repoCreateCourse,
  updateCourse as repoUpdateCourse,
  createLesson as repoCreateLesson,
  updateLesson as repoUpdateLesson,
  createNote as repoCreateNote,
  updateNote as repoUpdateNote,
  createCourseCard,
  createLessonCard,
  updateCard as repoUpdateCard,
  linkCardToLesson as repoLinkCardToLesson,
  createSequence as repoCreateSequence,
  updateSequence as repoUpdateSequence,
  createCourseAssessment as repoCreateCourseAssessment,
  updateCourseAssessment as repoUpdateCourseAssessment,
} from '../../db/repository';
import {
  createOcclusion as repoCreateOcclusion,
  updateOcclusion as repoUpdateOcclusion,
} from '../../db/occlusionRepository';
import type {
  occlusionRegionSchema} from '../contracts/content';
import {
  createCardContract,
  createCourseAssessmentContract,
  createCourseContract,
  createLessonContract,
  createNoteContract,
  createOcclusionContract,
  createSequenceContract,
  linkCardToLessonContract,
  updateCardContract,
  updateCourseAssessmentContract,
  updateCourseContract,
  updateLessonContract,
  updateNoteContract,
  updateOcclusionContract,
  updateSequenceContract,
} from '../contracts/content';
import { McpToolException, type ToolDefinition, type ToolResult } from '../types';

function ok<T>(data: T): ToolResult<T> {
  return { data };
}

function notFound(kind: string, id: string): never {
  throw new McpToolException({ kind: 'not_found', message: `${kind} "${id}" was not found.` });
}

function refuseGeneratedCard(cardId: string, source: 'sequence' | 'occlusion'): never {
  const article = source === 'sequence' ? 'a' : 'an';
  const via = source === 'sequence' ? 'that sequence (lacuna.update_sequence)' : 'that occlusion';
  throw new McpToolException({
    kind: 'conflict',
    message: `Card "${cardId}" was generated by ${article} ${source} and can only be edited via ${via}, not directly.`,
  });
}

// ---------------------------------------------------------------------------
// Courses
// ---------------------------------------------------------------------------

const createCourse: ToolDefinition<
  z.infer<typeof createCourseContract.inputSchema>,
  Awaited<ReturnType<typeof repoCreateCourse>>
> = {
  ...createCourseContract,
  async handler({ name, description }) {
    return ok(
      await repoCreateCourse(name, description !== undefined ? { description } : undefined),
    );
  },
};

const updateCourse: ToolDefinition<z.infer<typeof updateCourseContract.inputSchema>, { id: string }> = {
  ...updateCourseContract,
  async handler({ courseId, ...changes }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    const { examDate, ...courseChanges } = changes;
    if (Object.keys(courseChanges).length > 0) {
      await repoUpdateCourse(courseId, courseChanges);
    }
    if (examDate !== undefined) {
      const finalAssessment = await db.courseAssessments
        .where('courseId')
        .equals(courseId)
        .filter((assessment) => assessment.kind === 'final')
        .first();
      if (!finalAssessment) notFound('Final assessment for course', courseId);
      await repoUpdateCourseAssessment(finalAssessment.id, { examDate });
    }
    return ok({ id: courseId });
  },
};

// ---------------------------------------------------------------------------
// Lessons
// ---------------------------------------------------------------------------

const createLesson: ToolDefinition<
  z.infer<typeof createLessonContract.inputSchema>,
  Awaited<ReturnType<typeof repoCreateLesson>>
> = {
  ...createLessonContract,
  async handler({ courseId, name, description }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    return ok(
      await repoCreateLesson(
        courseId,
        name,
        description !== undefined ? { description } : undefined,
      ),
    );
  },
};

const updateLesson: ToolDefinition<z.infer<typeof updateLessonContract.inputSchema>, { id: string }> = {
  ...updateLessonContract,
  async handler({ lessonId, ...changes }) {
    if (!(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
    await repoUpdateLesson(lessonId, changes);
    return ok({ id: lessonId });
  },
};

// ---------------------------------------------------------------------------
// Notes
// ---------------------------------------------------------------------------

const createNote: ToolDefinition<
  z.infer<typeof createNoteContract.inputSchema>,
  Awaited<ReturnType<typeof repoCreateNote>>
> = {
  ...createNoteContract,
  async handler({ lessonId, name, content }) {
    if (!(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
    return ok(await repoCreateNote(lessonId, name, content));
  },
};

const updateNote: ToolDefinition<z.infer<typeof updateNoteContract.inputSchema>, { id: string }> = {
  ...updateNoteContract,
  async handler({ noteId, ...changes }) {
    if (!(await db.notes.get(noteId))) notFound('Note', noteId);
    await repoUpdateNote(noteId, changes);
    return ok({ id: noteId });
  },
};

// ---------------------------------------------------------------------------
// Cards
// ---------------------------------------------------------------------------

const createCard: ToolDefinition<
  z.infer<typeof createCardContract.inputSchema>,
  Awaited<ReturnType<typeof createCourseCard>>
> = {
  ...createCardContract,
  async handler({ courseId, lessonId, type, front, back, tags }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    if (lessonId !== undefined) {
      if (!(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
      return ok(await createLessonCard(courseId, lessonId, type, front, back, tags));
    }
    return ok(await createCourseCard(courseId, type, front, back, tags));
  },
};

const updateCard: ToolDefinition<z.infer<typeof updateCardContract.inputSchema>, { id: string }> = {
  ...updateCardContract,
  async handler({ cardId, ...changes }) {
    const card = await read.getCard(cardId);
    if (!card) notFound('Card', cardId);
    if (card.sequenceItemId !== undefined) refuseGeneratedCard(cardId, 'sequence');
    if (card.occlusionRegionId !== undefined) refuseGeneratedCard(cardId, 'occlusion');
    await repoUpdateCard(cardId, changes);
    return ok({ id: cardId });
  },
};

const linkCardToLesson: ToolDefinition<
  z.infer<typeof linkCardToLessonContract.inputSchema>,
  Awaited<ReturnType<typeof repoLinkCardToLesson>>
> = {
  ...linkCardToLessonContract,
  async handler({ lessonId, cardId }) {
    if (!(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
    if (!(await read.getCard(cardId))) notFound('Card', cardId);
    return ok(await repoLinkCardToLesson(lessonId, cardId));
  },
};

// ---------------------------------------------------------------------------
// Sequences
// ---------------------------------------------------------------------------

const createSequence: ToolDefinition<
  z.infer<typeof createSequenceContract.inputSchema>,
  Awaited<ReturnType<typeof repoCreateSequence>>
> = {
  ...createSequenceContract,
  async handler({ courseId, lessonId, name, items, cueWindow, mode, mySpeaker }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    if (lessonId !== undefined && !(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
    const opts: Partial<Awaited<ReturnType<typeof repoCreateSequence>>> = {};
    if (cueWindow !== undefined) opts.cueWindow = cueWindow;
    if (mode !== undefined) opts.mode = mode;
    if (mySpeaker !== undefined) opts.mySpeaker = mySpeaker;
    return ok(await repoCreateSequence(courseId, lessonId ?? null, name, items, opts));
  },
};

const updateSequence: ToolDefinition<z.infer<typeof updateSequenceContract.inputSchema>, { id: string }> = {
  ...updateSequenceContract,
  async handler({ sequenceId, name, items, cueWindow }) {
    const existing = await read.getSequence(sequenceId);
    if (!existing) notFound('Sequence', sequenceId);
    await repoUpdateSequence({
      ...existing,
      ...(name !== undefined ? { name } : {}),
      ...(items !== undefined ? { items } : {}),
      ...(cueWindow !== undefined ? { cueWindow } : {}),
    });
    return ok({ id: sequenceId });
  },
};

// ---------------------------------------------------------------------------
// Image occlusions
// ---------------------------------------------------------------------------

// `assetHash` must name a diagram already stored in this install: there is no
// asset-upload tool, deliberately, since binary transport is not a natural MCP shape.
// An agent authoring an SVG diagram plus fractional coordinates is the intended path once
// the user has uploaded (or the agent has otherwise produced) the image (Arc 6 §6.7).
/** Reject region references the occlusion itself cannot satisfy, before they reach the
 *  generator: a pairing must name a label region present in the same occlusion. */
function assertOcclusionRegionsResolve(regions: z.infer<typeof occlusionRegionSchema>[]): void {
  const byId = new Map(regions.map((region) => [region.id, region]));
  if (byId.size !== regions.length) {
    throw new McpToolException({
      kind: 'validation',
      message: 'Occlusion region ids must be unique within the occlusion.',
    });
  }
  for (const region of regions) {
    if (region.pairedRegionId === undefined) continue;
    const paired = byId.get(region.pairedRegionId);
    if (!paired || paired.role !== 'label') {
      throw new McpToolException({
        kind: 'validation',
        message: `Region "${region.id}" is paired to "${region.pairedRegionId}", which is not a label region in this occlusion.`,
      });
    }
  }
}

async function assertAssetExists(assetHash: string): Promise<void> {
  if (!(await db.assets.get(assetHash))) notFound('Asset', assetHash);
}

const createOcclusion: ToolDefinition<
  z.infer<typeof createOcclusionContract.inputSchema>,
  Awaited<ReturnType<typeof repoCreateOcclusion>>
> = {
  ...createOcclusionContract,
  async handler({ courseId, lessonId, name, assetHash, regions }) {
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    if (lessonId !== undefined && !(await read.getLesson(lessonId))) notFound('Lesson', lessonId);
    await assertAssetExists(assetHash);
    assertOcclusionRegionsResolve(regions);
    return ok(await repoCreateOcclusion(courseId, lessonId ?? null, name, assetHash, regions));
  },
};

const updateOcclusion: ToolDefinition<z.infer<typeof updateOcclusionContract.inputSchema>, { id: string }> = {
  ...updateOcclusionContract,
  async handler({ occlusionId, name, assetHash, regions }) {
    const existing = await read.getOcclusion(occlusionId);
    if (!existing) notFound('Occlusion', occlusionId);
    if (assetHash !== undefined) await assertAssetExists(assetHash);
    if (regions !== undefined) assertOcclusionRegionsResolve(regions);
    await repoUpdateOcclusion({
      ...existing,
      ...(name !== undefined ? { name } : {}),
      ...(assetHash !== undefined ? { assetHash } : {}),
      ...(regions !== undefined ? { regions } : {}),
    });
    return ok({ id: occlusionId });
  },
};

// ---------------------------------------------------------------------------
// Assessments
// ---------------------------------------------------------------------------

const createCourseAssessment: ToolDefinition<
  z.infer<typeof createCourseAssessmentContract.inputSchema>,
  Awaited<ReturnType<typeof repoCreateCourseAssessment>>
> = {
  ...createCourseAssessmentContract,
  async handler(input) {
    const { courseId, name, examDate, ...options } = input;
    if (!(await read.getCourse(courseId))) notFound('Course', courseId);
    return ok(await repoCreateCourseAssessment(courseId, name, examDate, options));
  },
};

const updateCourseAssessment: ToolDefinition<
  z.infer<typeof updateCourseAssessmentContract.inputSchema>,
  { id: string }
> = {
  ...updateCourseAssessmentContract,
  async handler({ assessmentId, ...changes }) {
    if (!(await db.courseAssessments.get(assessmentId)))
      notFound('Course assessment', assessmentId);
    await repoUpdateCourseAssessment(
      assessmentId,
      (changes.coverageMode === 'prefix'
        ? { ...changes, lessonIds: undefined }
        : changes) as Partial<CourseAssessment>,
    );
    return ok({ id: assessmentId });
  },
};

/** The content CRUD tool group, in the order they appear in Arc 2 §2.3's inventory. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- a heterogeneous tool list is necessarily ToolDefinition<any, any>; each entry above is still checked against its own concrete Input/Output.
export const CONTENT_TOOLS: readonly ToolDefinition<any, any>[] = [
  createCourse,
  updateCourse,
  createLesson,
  updateLesson,
  createNote,
  updateNote,
  createCard,
  updateCard,
  linkCardToLesson,
  createSequence,
  updateSequence,
  createOcclusion,
  updateOcclusion,
  createCourseAssessment,
  updateCourseAssessment,
];

// Also export individually for direct handler-level unit tests.
export {
  createCourse,
  updateCourse,
  createLesson,
  updateLesson,
  createNote,
  updateNote,
  createCard,
  updateCard,
  linkCardToLesson,
  createSequence,
  updateSequence,
  createOcclusion,
  updateOcclusion,
  createCourseAssessment,
  updateCourseAssessment,
};
