// The destructive/bulk tool group (Arc 2 §2.3): thin wrappers over src/db/repository.ts's
// existing snapshot/undo primitives, gated behind the 'destructive' scope. Every tool that
// removes or bulk-mutates content captures a snapshot first (where the repository offers
// one) and attaches it to the result's internal `undo` envelope field (src/mcp/types.ts) —
// never in `data`, which is what the calling agent actually sees. The bridge layer
// (a later task) reads `undo` to offer an in-app undo toast identical to the DangerZone
// pattern, then strips it before replying over IPC.
//
// `lacuna.delete_card` refuses sequence-generated cards: `deleteCards` already enforces
// this via `assertNoGeneratedCards`, thrown as a plain Error, so it is translated into a
// `conflict` McpToolError here rather than leaking as `internal`.

import { z } from 'zod';
import * as read from '../../db/read';
import {
  deleteCards,
  snapshotCards,
  deleteLesson as repoDeleteLesson,
  snapshotLesson,
  deleteCourse as repoDeleteCourse,
  snapshotCourse,
  deleteSequence as repoDeleteSequence,
  snapshotSequence,
  setCardsSuspended,
  setCardFlag,
  rescheduleCards as repoRescheduleCards,
} from '../../db/repository';
import { McpToolException, type ToolDefinition, type ToolResult } from '../types';

const cardIdsSchema = z.array(z.string()).min(1).describe('Card ids to act on.');

function ok<T>(data: T, undo?: ToolResult<T>['undo']): ToolResult<T> {
  return undo !== undefined ? { data, undo } : { data };
}

function notFound(kind: string, id: string): never {
  throw new McpToolException({ kind: 'not_found', message: `${kind} "${id}" was not found.` });
}

/** Resolve card ids to existing rows, throwing not_found for anything missing. */
async function requireCards(ids: string[]): Promise<void> {
  for (const id of ids) {
    if (!(await read.getCard(id))) notFound('Card', id);
  }
}

// ---------------------------------------------------------------------------
// Cards
// ---------------------------------------------------------------------------

const deleteCardSchema = z.object({ ids: cardIdsSchema });
const deleteCard: ToolDefinition<z.infer<typeof deleteCardSchema>, { deletedCount: number }> = {
  name: 'lacuna.delete_card',
  description:
    'Permanently delete one or more cards. Refuses cards generated by a sequence — delete or ' +
    'edit those via lacuna.update_sequence/lacuna.delete_sequence instead.',
  inputSchema: deleteCardSchema,
  requiredScope: 'destructive',
  async handler({ ids }) {
    await requireCards(ids);
    const snapshot = await snapshotCards(ids);
    try {
      await deleteCards(ids);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      throw new McpToolException({ kind: 'conflict', message });
    }
    return ok({ deletedCount: ids.length }, { kind: 'restoreCards', snapshot });
  },
};

const suspendCardsSchema = z.object({
  ids: cardIdsSchema,
  suspended: z.boolean().describe('true to suspend (withhold from study), false to un-suspend.'),
});
const suspendCards: ToolDefinition<z.infer<typeof suspendCardsSchema>, { updatedCount: number }> = {
  name: 'lacuna.suspend_cards',
  description: 'Suspend or un-suspend one or more cards, withholding/restoring them from study and progress.',
  inputSchema: suspendCardsSchema,
  requiredScope: 'destructive',
  async handler({ ids, suspended }) {
    await requireCards(ids);
    const snapshot = await snapshotCards(ids);
    await setCardsSuspended(ids, suspended);
    return ok({ updatedCount: ids.length }, { kind: 'restoreCards', snapshot });
  },
};

const setCardsFlagSchema = z.object({
  ids: cardIdsSchema,
  flagged: z.boolean().describe('true to flag, false to clear the flag.'),
});
const setCardsFlagTool: ToolDefinition<z.infer<typeof setCardsFlagSchema>, { updatedCount: number }> = {
  name: 'lacuna.set_cards_flag',
  description: "Set or clear one or more cards' flag, a marker for quick filtering and follow-up.",
  inputSchema: setCardsFlagSchema,
  requiredScope: 'destructive',
  async handler({ ids, flagged }) {
    await requireCards(ids);
    const snapshot = await snapshotCards(ids);
    await Promise.all(ids.map((id) => setCardFlag(id, flagged)));
    return ok({ updatedCount: ids.length }, { kind: 'restoreCards', snapshot });
  },
};

const rescheduleCardsSchema = z
  .object({
    ids: cardIdsSchema,
    reset: z.boolean().optional().describe('Reset selected cards to the New state, clearing all scheduling data.'),
    due: z.number().optional().describe('Set a specific due date, as an epoch millisecond value. Takes precedence over reset.'),
  })
  .refine((v) => v.reset === true || v.due !== undefined, {
    message: 'reschedule_cards requires either reset: true or a due date.',
  });
const rescheduleCardsTool: ToolDefinition<z.infer<typeof rescheduleCardsSchema>, { updatedCount: number }> = {
  name: 'lacuna.reschedule_cards',
  description:
    'Bulk-reschedule cards: either reset them to New (clearing stability, difficulty, due, etc.) or ' +
    'set a custom due date. Never writes raw FSRS fields directly — bounded to these two options.',
  inputSchema: rescheduleCardsSchema,
  requiredScope: 'destructive',
  async handler({ ids, reset, due }) {
    await requireCards(ids);
    const snapshot = await snapshotCards(ids);
    await repoRescheduleCards(ids, reset !== undefined ? { reset, due } : { due });
    return ok({ updatedCount: ids.length }, { kind: 'restoreCards', snapshot });
  },
};

// ---------------------------------------------------------------------------
// Lessons / courses / sequences
// ---------------------------------------------------------------------------

const deleteLessonSchema = z.object({ lessonId: z.string().describe('The id of the lesson to delete.') });
const deleteLessonTool: ToolDefinition<z.infer<typeof deleteLessonSchema>, { id: string }> = {
  name: 'lacuna.delete_lesson',
  description:
    "Delete a lesson: its notes and lesson-card links are removed, but cards whose primary " +
    'lesson was this one become unassigned (kept in the course question bank) rather than deleted.',
  inputSchema: deleteLessonSchema,
  requiredScope: 'destructive',
  async handler({ lessonId }) {
    const snapshot = await snapshotLesson(lessonId);
    if (!snapshot) notFound('Lesson', lessonId);
    await repoDeleteLesson(lessonId);
    return ok({ id: lessonId }, { kind: 'restoreLesson', snapshot });
  },
};

const deleteCourseSchema = z.object({ courseId: z.string().describe('The id of the course to delete.') });
const deleteCourseTool: ToolDefinition<z.infer<typeof deleteCourseSchema>, { id: string }> = {
  name: 'lacuna.delete_course',
  description: 'Permanently delete a course and everything in it: lessons, notes, cards, sequences and exam dates.',
  inputSchema: deleteCourseSchema,
  requiredScope: 'destructive',
  async handler({ courseId }) {
    const snapshot = await snapshotCourse(courseId);
    if (!snapshot) notFound('Course', courseId);
    await repoDeleteCourse(courseId);
    return ok({ id: courseId }, { kind: 'restoreCourse', snapshot });
  },
};

const deleteSequenceSchema = z.object({ sequenceId: z.string().describe('The id of the sequence to delete.') });
const deleteSequenceTool: ToolDefinition<z.infer<typeof deleteSequenceSchema>, { id: string }> = {
  name: 'lacuna.delete_sequence',
  description: 'Permanently delete a sequence and every card it generated.',
  inputSchema: deleteSequenceSchema,
  requiredScope: 'destructive',
  async handler({ sequenceId }) {
    const snapshot = await snapshotSequence(sequenceId);
    if (!snapshot) notFound('Sequence', sequenceId);
    await repoDeleteSequence(sequenceId);
    return ok({ id: sequenceId }, { kind: 'restoreSequence', snapshot });
  },
};

/** The destructive/bulk tool group, in the order they appear in Arc 2 §2.3's inventory. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- a heterogeneous tool list is necessarily ToolDefinition<any, any>; each entry above is still checked against its own concrete Input/Output.
export const DESTRUCTIVE_TOOLS: readonly ToolDefinition<any, any>[] = [
  deleteCard,
  deleteLessonTool,
  deleteCourseTool,
  deleteSequenceTool,
  suspendCards,
  setCardsFlagTool,
  rescheduleCardsTool,
];

// Also export individually for direct handler-level unit tests.
export {
  deleteCard,
  deleteLessonTool as deleteLesson,
  deleteCourseTool as deleteCourse,
  deleteSequenceTool as deleteSequence,
  suspendCards,
  setCardsFlagTool as setCardsFlag,
  rescheduleCardsTool as rescheduleCards,
};
