// IPC envelope shared by the Electron main process (electron/mcp/server.ts, which owns
// the MCP SDK's stdio transport) and the renderer (src/mcp/bridge/renderer.ts, which is
// the only process with IndexedDB and therefore the only process that can execute a tool
// handler). See next_plan.md's Arc 2 §2.1 "Core module split" for the full rationale.
//
// This module is types only — no runtime transport code lives here. The MCP SDK itself
// must never be imported from anywhere under src/, since src/ is bundled into both the
// Electron renderer and the Cloudflare web build, and neither hosts a server.

/** A tool invocation request sent from the main process to the renderer. */
export interface McpInvokeRequest {
  /** Correlation id, generated by the main process, echoed back on the response. */
  id: string;
  /** Tool name, e.g. "lacuna.list_courses" (see src/mcp/registry.ts). */
  tool: string;
  /** Raw (not yet validated) tool input, as supplied by the MCP client. */
  input: unknown;
  /** Identifies the calling MCP server process for grant resolution (see §2.4). */
  agentId: string;
}

/** A tool invocation response sent from the renderer back to the main process. */
export type McpInvokeResponse =
  | { id: string; ok: true; result: unknown }
  | { id: string; ok: false; error: McpToolError };

/**
 * Errors a tool handler can produce. Kept as a small discriminated union (rather than
 * throwing arbitrary Errors) so the main-process side can map each kind to a proper MCP
 * error result instead of leaking renderer stack traces to the calling agent.
 */
export type McpToolError =
  | { kind: 'not_found'; message: string }
  | { kind: 'validation'; message: string }
  | { kind: 'forbidden'; message: string }
  | { kind: 'conflict'; message: string }
  | { kind: 'internal'; message: string };
