import { z } from 'zod';
import {
  answerMode,
  card,
  cardContent,
  dispute,
  flag,
  grade,
  id,
  ids,
  lesson,
  lessonContent,
  note,
  noteContent,
  number,
  object,
  parameters,
  payload,
  schedule,
  strings,
  text,
  timestamps,
  verdict,
} from './backupRecordSchemas';
import { isAgentMemory } from './agentMemoryRecord';

const projection = z.discriminatedUnion('projectionMode', [
  object({ projectionMode: z.literal('memory-model'), memoryModelVersion: text }),
  object({
    projectionMode: z.literal('fsrs-6-practice-fallback'),
    memoryModelVersion: z.literal('fsrs-6'),
    fallbackReason: z.enum(['missing', 'corrupt', 'unsupported']),
  }),
]);
const input = object({
  coverageVersion: text,
  deadlineAt: number,
  timeZone: text.optional(),
  reachedLessonIds: ids,
  exposureVersion: text,
  availabilityVersion: text,
  reviewEvidenceVersion: text,
  projection,
});
const scope = object({
  coveredLessonIds: ids,
  excludedCardIds: ids,
  eligibleCardIds: ids,
  unavailableCardIds: ids,
  unreachedLessonIds: ids,
  untaughtLessonIds: ids,
});
const cardStates = z.array(object({ cardId: id, status: z.enum(['eligible', 'unavailable']) }));
const reasons = z.array(
  z.enum([
    'assessment-coverage-changed',
    'assessment-deadline-changed',
    'assessment-time-zone-changed',
    'memory-model-changed',
    'reached-lessons-changed',
    'card-exposure-changed',
    'card-availability-changed',
    'review-evidence-changed',
  ]),
);
const baseline = z.discriminatedUnion('kind', [
  object({ kind: z.literal('new') }),
  object({ kind: z.literal('legacy-replayable'), sourceCardId: id, sourceReviewIds: ids }),
  object({
    kind: z.literal('legacy-opaque'),
    sourceCardId: id,
    state: object(schedule),
    reason: z.enum(['missing-history', 'inconsistent-history']),
  }),
]);
const questionBase = object({
  ...schedule,
  ...timestamps,
  id,
  courseId: id,
  primaryLessonId: id.nullable(),
  additionalLessonIds: ids,
  name: text,
  tags: strings,
  suspended: flag,
  contentVersion: number,
  contentRevisionId: id,
  authoringRevisionId: id,
  authoringUpdatedAt: number,
  scheduleEpoch: object({
    id,
    startedAt: number,
    reason: z.enum(['created', 'semantic-edit', 'legacy-card-migration']),
    baseline,
  }),
  scheduleUpdatedAt: number,
});
const questionPayload = payload.refine(
  (value) => value !== undefined && value !== null,
  'Question payload is required',
);
const submittedAnswer = z.union([text, strings]);
const incomingCard = object({
  i: id,
  k: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
  f: text,
  b: text.optional(),
  g: strings.optional(),
  p: payload.optional(),
  am: answerMode,
});
const incomingNote = object({ i: id, n: text, c: text });
const incomingLesson = object({
  i: id,
  n: text,
  d: text.optional(),
  x: z.union([z.literal(0), z.literal(1)]).optional(),
  rd: number.optional(),
  ed: number.optional(),
  tz: text.optional(),
  sf: z.enum(['due', 'mixed']).optional(),
  notes: z.array(incomingNote),
  cards: z.array(incomingCard),
  am: answerMode,
});

export const stateSchemas = {
  revisionPlans: object({
    ...timestamps,
    id,
    assessmentId: id,
    courseId: id,
    status: z.enum(['active', 'completed']),
    revision: number,
    input,
    scope,
    cardStates,
    windows: z.array(
      object({
        id,
        day: text,
        budgetMinutes: number,
        status: z.enum(['scheduled', 'active', 'completed']),
        planRevision: number,
        startedAt: number.optional(),
        completedAt: number.optional(),
      }),
    ),
    completedSessions: z.array(
      object({
        id,
        windowId: id,
        startedAt: number,
        completedAt: number,
        cardIds: ids,
        reviewEventIds: ids,
        improvedCardIds: ids.optional(),
        parkedCardIds: ids.optional(),
      }),
    ),
    replans: z.array(
      object({ id, revision: number, reasons, explanation: text, appliedAt: number }),
    ),
    pendingReplan: object({ reasons, requestedAt: number, input, scope, cardStates }).optional(),
  }),
  concepts: z.discriminatedUnion('scope', [
    object({
      ...timestamps,
      id,
      scopeKey: id,
      name: text,
      provisional: flag,
      scope: z.literal('course'),
      courseId: id,
    }),
    object({
      ...timestamps,
      id,
      scopeKey: id,
      name: text,
      provisional: z.literal(true),
      scope: z.literal('legacy-scheduling-unit'),
      courseId: z.null(),
      legacySchedulingUnitId: id,
    }),
  ]),
  questions: z.discriminatedUnion('kind', [
    questionBase.extend({
      kind: z.literal('fixed'),
      prompt: text,
      payload: questionPayload,
      explanation: text,
      explanationStatus: z.enum(['authored', 'legacy-derived']),
    }),
    questionBase.extend({
      kind: z.literal('generated'),
      generatorKey: id,
      generatorVersion: number,
      generatorConfig: z.unknown(),
    }),
  ]),
  questionConcepts: object({
    ...timestamps,
    questionId: id,
    courseId: id,
    targetConceptIds: ids,
    prerequisiteConceptIds: ids,
    authoringRevisionId: id,
    authoringUpdatedAt: number,
  }),
  questionAttempts: object({
    id,
    questionId: id,
    courseId: id,
    contentVersion: number,
    contentRevisionId: id,
    scheduleEpochId: id,
    purpose: z.literal('post-instruction'),
    shownAt: number,
    answeredAt: number.optional(),
    abandonedAt: number.optional(),
    undoneAt: number.optional(),
    updatedAt: number,
    status: z.enum(['shown', 'answered', 'abandoned']),
    receiptOrigin: z.enum(['native', 'legacy-reconstructed']),
    sourceCardId: id.optional(),
    sourceReviewId: id.optional(),
    historicalPresentationKnown: z.literal(false).optional(),
    submittedAnswerKnown: flag.optional(),
    generatorKey: id.optional(),
    generatorVersion: number.optional(),
    seed: text.optional(),
    parameters: z.record(text, z.union([text, number, flag])).optional(),
    generatorFingerprint: text.optional(),
    renderedPrompt: text,
    resolvedPayload: questionPayload,
    renderedExplanation: text,
    submittedAnswer: submittedAnswer.optional(),
    marksEarned: number.optional(),
    marksAvailable: number.optional(),
    lineVerdicts: z.array(verdict).optional(),
    checkerDisputes: z.array(dispute).optional(),
    correction: object({
      submittedAt: number,
      submittedAnswer,
      marksEarned: number,
      marksAvailable: number,
      lineVerdicts: z.array(verdict).optional(),
    }).optional(),
    responseTimeSeconds: number.optional(),
    grade: grade.optional(),
    retrievabilityAtAttempt: number.nullable().optional(),
    scheduleEffect: z.discriminatedUnion('kind', [
      object({ kind: z.literal('replay'), grade }),
      object({ kind: z.literal('included-in-opaque-baseline') }),
      object({ kind: z.literal('none') }),
    ]),
    schedulerVersion: z.literal('fsrs-6-question-v1').optional(),
    gradeMappingVersion: z.literal('full-good-otherwise-again-v1').optional(),
    schedulerConfigFingerprint: text.optional(),
    schedulerConfig: parameters.optional(),
    sessionId: id,
  }),
  lineageIdMappings: object({
    id,
    courseId: id,
    lessonIds: ids,
    noteIds: ids,
    cardIds: ids,
    conceptIds: ids.optional(),
    questionIds: ids.optional(),
    sequenceIds: ids,
    occlusionIds: ids.optional(),
    lessonSnapshots: z.record(text, lessonContent.omit({ unlockedAt: true })),
    noteSnapshots: z.record(text, noteContent),
    cardSnapshots: z.record(text, cardContent),
  }),
  pendingMergeReviews: object({
    id,
    courseId: id,
    lineageId: id,
    revision: number,
    createdAt: number,
    diff: object({
      creates: object({ lessons: z.array(lesson), notes: z.array(note), cards: z.array(card) }),
      updates: object({
        lessons: z.array(lessonContent.partial().extend({ id })),
        notes: z.array(noteContent.partial().extend({ id })),
        cards: z.array(cardContent.partial().extend({ id })),
      }),
      removals: object({ lessonIds: ids, noteIds: ids, cardIds: ids }),
      conflicts: z.array(
        z.discriminatedUnion('kind', [
          object({ entityId: id, kind: z.literal('lesson'), incoming: incomingLesson.nullable() }),
          object({ entityId: id, kind: z.literal('note'), incoming: incomingNote.nullable() }),
          object({ entityId: id, kind: z.literal('card'), incoming: incomingCard.nullable() }),
        ]),
      ),
    }),
  }),
  agentMemories: z.custom(isAgentMemory, 'Invalid agent memory'),
};
