import { z } from 'zod';
import type { ToolContract } from '../types';

const courseIdSchema = z.string().describe('The id of the course.');
const lessonIdSchema = z.string().describe('The id of the lesson.');

export const createCourseContract = {
  name: 'lacuna.create_course',
  description:
    'Create a new course with sensible scheduling defaults (exam date, FSRS parameters, unlock mode).',
  inputSchema: z.object({
    name: z.string().describe('The course name.'),
    description: z.string().optional().describe('Optional free-text description.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const updateCourseContract = {
  name: 'lacuna.update_course',
  description: "Update a course's name, description, and/or primary exam date.",
  inputSchema: z.object({
    courseId: courseIdSchema,
    name: z.string().optional().describe('New course name.'),
    description: z.string().optional().describe('New free-text description.'),
    examDate: z.number().optional().describe('New primary exam date/time, as an epoch millisecond value in UTC.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const createLessonContract = {
  name: 'lacuna.create_lesson',
  description: "Create a new lesson at the end of a course's path.",
  inputSchema: z.object({
    courseId: courseIdSchema,
    name: z.string().describe('The lesson name.'),
    description: z.string().optional().describe('Optional free-text description.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const updateLessonContract = {
  name: 'lacuna.update_lesson',
  description: "Update a lesson's name and/or description.",
  inputSchema: z.object({
    lessonId: lessonIdSchema,
    name: z.string().optional().describe('New lesson name.'),
    description: z.string().optional().describe('New free-text description.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const createNoteContract = {
  name: 'lacuna.create_note',
  description: "Create a new Markdown note at the end of a lesson's notes.",
  inputSchema: z.object({
    lessonId: lessonIdSchema,
    name: z.string().describe('The note name.'),
    content: z.string().optional().describe('Rich Markdown source. Defaults to empty.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const updateNoteContract = {
  name: 'lacuna.update_note',
  description: "Update a note's name and/or Markdown content.",
  inputSchema: z.object({
    noteId: z.string().describe('The id of the note to update.'),
    name: z.string().optional().describe('New note name.'),
    content: z.string().optional().describe('New Markdown source.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

const cardTypeSchema = z.enum(['front_back', 'cloze', 'basic_reversed']).describe('The card type.');

export const createCardContract = {
  name: 'lacuna.create_card',
  description:
    "Create a new card, either unassigned in a course's question bank or assigned to a lesson " +
    'when lessonId is given.',
  inputSchema: z.object({
    courseId: courseIdSchema,
    lessonId: z.string().optional().describe(
      'If given, create the card in this lesson. Otherwise create it unassigned, in the course question bank.',
    ),
    type: cardTypeSchema,
    front: z.string().describe('Markdown source for the question/prompt side.'),
    back: z.string().describe('Markdown source for the answer side. Unused (empty) for cloze cards.'),
    tags: z.array(z.string()).optional().describe('Free-text tags. Defaults to none.'),
  }).strict(),
  requiredScope: 'write',
} satisfies ToolContract;

export const updateCardContract = {
  name: 'lacuna.update_card',
  description:
    "Update a card's content: front, back, tags, and/or flagged state. Never touches FSRS " +
    "scheduling fields (state, stability, difficulty, due) — those are the study engine's " +
    'exclusive write path. Refuses cards generated by a sequence or an occlusion; edit ' +
    'those via their owning sequence (lacuna.update_sequence) or occlusion.',
  inputSchema: z.object({
    cardId: z.string().describe('The id of the card to update.'),
    front: z.string().optional().describe('New Markdown source for the question/prompt side.'),
    back: z.string().optional().describe('New Markdown source for the answer side.'),
    tags: z.array(z.string()).optional().describe('Replacement set of free-text tags.'),
    flagged: z.boolean().optional().describe('New flagged state, for quick filtering/follow-up.'),
  }).strict(),
  requiredScope: 'write',
} satisfies ToolContract;

export const linkCardToLessonContract = {
  name: 'lacuna.link_card_to_lesson',
  description:
    'Display-link an existing card into an additional lesson, alongside its primary lesson. ' +
    'Idempotent: linking an already-linked card is a no-op that returns the existing link.',
  inputSchema: z.object({
    lessonId: lessonIdSchema,
    cardId: z.string().describe('The id of the card to link.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const sequenceItemSchema = z.object({
  id: z.string().describe('Stable id for this item — anchors the card(s) generated from it across edits.'),
  value: z.string().describe('Markdown source for the recallable unit.'),
  label: z.string().optional().describe('Optional display key (e.g. "11" for Sodium).'),
  chunkIndex: z.number().int().optional().describe('Membership of a named chunk (see chunkLabels).'),
  speaker: z.string().optional().describe('`lines` mode only: who speaks this line.'),
});

export const createSequenceContract = {
  name: 'lacuna.create_sequence',
  description:
    'Create a new overlapping-cloze sequence and, in the same transaction, every card it generates.',
  inputSchema: z.object({
    courseId: courseIdSchema,
    lessonId: z.string().optional().describe(
      'If given, scope the sequence (and its generated cards) to this lesson. Otherwise the course question bank.',
    ),
    name: z.string().describe('The sequence name.'),
    items: z.array(sequenceItemSchema).describe('Ordered recallable units the sequence generates cards from.'),
    cueWindow: z.number().int().optional().describe('How many preceding items are shown as cue. Defaults to 2.'),
    mode: z.enum(['list', 'lines']).optional().describe(
      '`list` (default): every item generates a positional recall card. `lines`: script mode, see mySpeaker.',
    ),
    mySpeaker: z.string().optional().describe('`lines` mode only: the speaker whose lines are the recall target.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const updateSequenceContract = {
  name: 'lacuna.update_sequence',
  description:
    "Update a sequence's name, items, and/or cue window, regenerating its cards to match. Card " +
    'content is diffed and updated in place where possible, so existing FSRS memory state ' +
    'survives content-only regeneration.',
  inputSchema: z.object({
    sequenceId: z.string().describe('The id of the sequence to update.'),
    name: z.string().optional().describe('New sequence name.'),
    items: z.array(sequenceItemSchema).optional().describe('Replacement ordered list of recallable units.'),
    cueWindow: z.number().int().optional().describe('New cue window.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const occlusionRegionSchema = z.object({
  id: z.string().describe('Stable id for this region — anchors the card generated from it across edits.'),
  role: z.enum(['label', 'feature']).describe(
    '`label`: masks text printed on the diagram, revealed by uncovering it. `feature`: points at part of the drawing and is answered by its paired label region.',
  ),
  shape: z.literal('rectangle').describe('Rectangles only in this version.'),
  x: z.number().describe('Left edge as a fraction of image width, 0..1.'),
  y: z.number().describe('Top edge as a fraction of image height, 0..1.'),
  w: z.number().describe('Width as a fraction of image width, 0..1.'),
  h: z.number().describe('Height as a fraction of image height, 0..1.'),
  answerText: z.string().optional().describe('Required for typed mode and for an unpaired feature region.'),
  pairedRegionId: z.string().optional().describe('`feature` regions only: the label region that answers this one.'),
  backNote: z.string().optional().describe('Optional extra shown below the image on the back.'),
});

export const createOcclusionContract = {
  name: 'lacuna.create_occlusion',
  description:
    'Create an image occlusion over an existing diagram and, in the same transaction, one card per region.',
  inputSchema: z.object({
    courseId: courseIdSchema,
    lessonId: z.string().optional().describe(
      'If given, scope the occlusion (and its generated cards) to this lesson. Otherwise the course question bank.',
    ),
    name: z.string().describe("The occlusion name, used in each generated card's text fallback."),
    assetHash: z.string().describe('Hash of a diagram already stored in this install (see lacuna.get_occlusion).'),
    regions: z.array(occlusionRegionSchema).describe(
      'The regions to generate one card each from. Every label region is masked on every front.',
    ),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const updateOcclusionContract = {
  name: 'lacuna.update_occlusion',
  description:
    "Update an occlusion's name, diagram and/or regions, regenerating its cards to match. Card " +
    'content is diffed and updated in place where possible, so existing FSRS memory state ' +
    'survives content-only regeneration (moving or resizing a region, re-pairing, role changes).',
  inputSchema: z.object({
    occlusionId: z.string().describe('The id of the occlusion to update.'),
    name: z.string().optional().describe('New occlusion name.'),
    assetHash: z.string().optional().describe('Replacement diagram. Regenerates every card in the occlusion.'),
    regions: z.array(occlusionRegionSchema).optional().describe('Replacement region list.'),
  }),
  requiredScope: 'write',
} satisfies ToolContract;

const assessmentCoverageSchema = z.discriminatedUnion('coverageMode', [
  z.object({ coverageMode: z.literal('prefix') }),
  z.object({ coverageMode: z.literal('custom'), lessonIds: z.array(z.string()).min(1) }),
]);

export const createCourseAssessmentContract = {
  name: 'lacuna.create_course_assessment',
  description:
    'Create a checkpoint assessment with explicit path placement, coverage and card exclusions.',
  inputSchema: z.object({
    courseId: courseIdSchema,
    name: z.string().describe('The checkpoint name.'),
    examDate: z.number().describe('The date/time as an epoch millisecond value, in UTC.'),
    timeZone: z.string().optional().describe('IANA time zone used to display the date.'),
    afterLessonId: z.string().nullable().describe('Path anchor; null places it before lesson one.'),
    excludedCardIds: z.array(z.string()).optional().describe('Covered cards to exclude.'),
  }).and(assessmentCoverageSchema),
  requiredScope: 'write',
} satisfies ToolContract;

export const updateCourseAssessmentContract = {
  name: 'lacuna.update_course_assessment',
  description: 'Update an assessment without changing its stable identity or course.',
  inputSchema: z.object({
    assessmentId: z.string().describe('The id of the assessment to update.'),
    name: z.string().optional().describe('New name.'),
    examDate: z.number().optional().describe('New date/time as an epoch millisecond value, in UTC.'),
    timeZone: z.string().optional().describe('New IANA display time zone.'),
    afterLessonId: z.string().nullable().optional().describe('New path anchor.'),
    coverageMode: z.enum(['prefix', 'custom']).optional().describe('New coverage mode.'),
    lessonIds: z.array(z.string()).min(1).optional().describe('Explicit custom lesson ids.'),
    excludedCardIds: z.array(z.string()).optional().describe('Replacement excluded card ids.'),
    needsAuthorConfirmation: z.boolean().optional().describe('Whether an author must review references.'),
  }).superRefine((value, context) => {
    if (value.lessonIds !== undefined && value.coverageMode !== 'custom') {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['coverageMode'],
        message: 'lessonIds requires coverageMode "custom".',
      });
    }
    if (value.coverageMode === 'custom' && value.lessonIds === undefined) {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['lessonIds'],
        message: 'Custom coverage requires lessonIds.',
      });
    }
  }),
  requiredScope: 'write',
} satisfies ToolContract;

export const CONTENT_TOOL_CONTRACTS = [
  createCourseContract,
  updateCourseContract,
  createLessonContract,
  updateLessonContract,
  createNoteContract,
  updateNoteContract,
  createCardContract,
  updateCardContract,
  linkCardToLessonContract,
  createSequenceContract,
  updateSequenceContract,
  createOcclusionContract,
  updateOcclusionContract,
  createCourseAssessmentContract,
  updateCourseAssessmentContract,
] as const satisfies readonly ToolContract[];
