import { z } from 'zod';
import type { ToolContract } from '../types';

const cardIdsSchema = z.array(z.string()).min(1).describe('Card ids to act on.');

export const deleteCardContract = {
  name: 'lacuna.delete_card',
  description:
    'Permanently delete one or more cards. Refuses cards generated by a sequence — delete or ' +
    'edit those via lacuna.update_sequence/lacuna.delete_sequence instead.',
  inputSchema: z.object({ ids: cardIdsSchema }),
  requiredScope: 'destructive',
} satisfies ToolContract;

export const suspendCardsContract = {
  name: 'lacuna.suspend_cards',
  description: 'Suspend or un-suspend one or more cards, withholding/restoring them from study and progress.',
  inputSchema: z.object({
    ids: cardIdsSchema,
    suspended: z.boolean().describe('true to suspend (withhold from study), false to un-suspend.'),
  }),
  requiredScope: 'destructive',
} satisfies ToolContract;

export const setCardsFlagContract = {
  name: 'lacuna.set_cards_flag',
  description: "Set or clear one or more cards' flag, a marker for quick filtering and follow-up.",
  inputSchema: z.object({
    ids: cardIdsSchema,
    flagged: z.boolean().describe('true to flag, false to clear the flag.'),
  }),
  requiredScope: 'destructive',
} satisfies ToolContract;

export const rescheduleCardsContract = {
  name: 'lacuna.reschedule_cards',
  description:
    'Bulk-reschedule cards: either reset them to New (clearing stability, difficulty, due, etc.) or ' +
    'set a custom due date. Never writes raw FSRS fields directly — bounded to these two options.',
  inputSchema: z.object({
    ids: cardIdsSchema,
    reset: z.boolean().optional().describe('Reset selected cards to the New state, clearing all scheduling data.'),
    due: z.number().optional().describe('Set a specific due date, as an epoch millisecond value. Takes precedence over reset.'),
  }).refine((value) => value.reset === true || value.due !== undefined, {
    message: 'reschedule_cards requires either reset: true or a due date.',
  }),
  requiredScope: 'destructive',
} satisfies ToolContract;

export const deleteLessonContract = {
  name: 'lacuna.delete_lesson',
  description:
    "Delete a lesson: its notes and lesson-card links are removed, but cards whose primary " +
    'lesson was this one become unassigned (kept in the course question bank) rather than deleted.',
  inputSchema: z.object({ lessonId: z.string().describe('The id of the lesson to delete.') }),
  requiredScope: 'destructive',
} satisfies ToolContract;

export const deleteCourseContract = {
  name: 'lacuna.delete_course',
  description: 'Permanently delete a course and everything in it: lessons, notes, cards, sequences and exam dates.',
  inputSchema: z.object({ courseId: z.string().describe('The id of the course to delete.') }),
  requiredScope: 'destructive',
} satisfies ToolContract;

export const deleteSequenceContract = {
  name: 'lacuna.delete_sequence',
  description: 'Permanently delete a sequence and every card it generated.',
  inputSchema: z.object({ sequenceId: z.string().describe('The id of the sequence to delete.') }),
  requiredScope: 'destructive',
} satisfies ToolContract;

export const deleteOcclusionContract = {
  name: 'lacuna.delete_occlusion',
  description: 'Permanently delete an image occlusion and every card it generated.',
  inputSchema: z.object({ occlusionId: z.string().describe('The id of the occlusion to delete.') }),
  requiredScope: 'destructive',
} satisfies ToolContract;

export const deleteCourseAssessmentContract = {
  name: 'lacuna.delete_course_assessment',
  description: 'Delete a checkpoint assessment. The sole final assessment cannot be deleted.',
  inputSchema: z.object({ assessmentId: z.string().describe('The id of the checkpoint assessment to delete.') }),
  requiredScope: 'destructive',
} satisfies ToolContract;

export const DESTRUCTIVE_TOOL_CONTRACTS = [
  deleteCardContract,
  deleteLessonContract,
  deleteCourseContract,
  deleteSequenceContract,
  deleteOcclusionContract,
  deleteCourseAssessmentContract,
  suspendCardsContract,
  setCardsFlagContract,
  rescheduleCardsContract,
] as const satisfies readonly ToolContract[];
