export const UI = {
  nav: {
    home: 'Home',
    decks: 'Decks',
    review: 'Review',
    notes: 'Notes',
    settings: 'Settings',
  },
  layout: {
    nav: 'Main navigation',
  },
  home: {
    heading: 'Lacuna',
    dueToday: (n: number) => `${n} card${n === 1 ? '' : 's'} due today`,
    startReview: 'Start revision',
    noCardsDue: 'No cards due. Come back later, or add a new deck.',
    viewDecks: 'View decks',
    upcomingExam: (deckName: string, days: number, readiness: number) =>
      `Your next exam is in ${days} day${days === 1 ? '' : 's'}. ${deckName} is ${readiness}% ready.`,
  },
  decks: {
    heading: 'Decks',
    loading: 'Loading decks...',
    errorLoad: 'Could not load decks.',
    empty: 'No decks yet. Create one to get started.',
    createDeck: 'New deck',
    deckName: 'Deck name',
    parentDeck: 'Parent deck (optional)',
    noParent: 'None (top-level deck)',
    rename: 'Rename',
    deleteDeck: 'Delete deck',
    renameDeck: 'Rename deck',
    renameHeading: 'Rename deck',
    deleteHeading: 'Delete deck',
    newName: 'New name',
    deleteConfirm: (name: string) =>
      `Delete "${name}" and all its sub-decks? This cannot be undone.`,
    examDate: 'Exam date',
    examDateNone: 'No exam date',
    examDateSet: 'Exam date set',
    setExamDate: 'Set exam date',
    clearExamDate: 'Clear exam date',
    examDateLabel: 'Exam date',
    examRevision: 'Exam revision',
    examDatePast: 'Exam date is in the past',
    cardCount: (n: number) => `${n} card${n === 1 ? '' : 's'}`,
    dueCount: (n: number) => `${n} due`,
    pathSeparator: '::',
    nested: 'Sub-deck',
    expand: 'Expand',
    collapse: 'Collapse',
    examReadiness: (pct: number) => `${pct}% exam ready`,
    examDailyRecommendation: (minutes: number) => `~${minutes} min today`,
    examOnTrack: 'On track',
    examBehind: 'Behind schedule',
    examPanel: 'Exam overview',
  },
  review: {
    heading: 'Review',
    flip: 'Show answer',
    showAnswer: 'Show answer',
    again: 'Again',
    hard: 'Hard',
    good: 'Good',
    easy: 'Easy',
    sessionComplete: 'Revision complete.',
    // Defined — not yet rendered in current UI
    cardsRemaining: (n: number) => `${n} card${n === 1 ? '' : 's'} remaining`,
    // Defined — not yet rendered in current UI
    exitSession: 'End session',
    // Defined — not yet rendered in current UI
    examModeActive: 'Exam mode active',
    // Defined — not yet rendered in current UI
    examWarning: (count: number, date: string) =>
      `At your current revision pace, you can meaningfully cover approximately ${count} cards before your exam on ${date}.`,
    sessionProgress: (reviewed: number, total: number) =>
      `${reviewed} / ${total}`,
    keyboardHint: (key: string) => `[${key}]`,
    noDueCards: 'No cards due for revision.',
    noDueCardsDetail: 'All cards in this deck are up to date.',
    startRevision: 'Start revision',
    dueCards: (n: number) => `${n} card${n === 1 ? '' : 's'} due`,
    sessionDuration: (mmss: string) => `Time: ${mmss}`,
    sessionTotal: (n: number) => `${n} card${n === 1 ? '' : 's'} reviewed`,
    backToDecks: 'Back to decks',
    ratingAgain: (preview: string) => `Again — ${preview}`,
    ratingHard: (preview: string) => `Hard — ${preview}`,
    ratingGood: (preview: string) => `Good — ${preview}`,
    ratingEasy: (preview: string) => `Easy — ${preview}`,
    examModeBanner: (examDate: string, daysLabel: string) =>
      `Exam mode — ${examDate} — ${daysLabel}`,
    examModeBannerFull: (
      date: string,
      days: string,
      readiness: number,
      minutes: number,
    ) =>
      `Exam mode — ${date} — ${days} — ${readiness}% ready — ~${minutes} min today`,
    examDaysToGo: (n: number) => `${n} day${n === 1 ? '' : 's'} to go`,
    examToday: 'Today',
    examPast: 'Past',
    examModeCapacityWarning: (
      reviewable: number,
      total: number,
      examDate: string,
    ) =>
      `At your current review pace, you can meaningfully cover approximately ${reviewable} of ${total} cards before your exam on ${examDate}.`,
    reviewWhatICan: 'Review what I can',
    startExamRevision: 'Exam revision',
  },
  notes: {
    heading: 'Notes',
    empty: 'No notes yet.',
    untitled: 'Untitled note',
    createNote: 'New note',
    deleteNote: 'Delete note',
    // Defined — not yet rendered in current UI
    linkToDeck: 'Link to deck',
    summarise: 'Summarise note',
    generateCards: 'Generate cards',
    saving: 'Saving…',
    saved: 'Saved',
    noNoteSelected: 'Select a note or create a new one.',
    newNoteForDeck: 'New note for this deck',
    linkedNotes: 'Notes',
    deleteConfirm: 'Delete this note? This cannot be undone.',
    toolbarLabel: 'Note formatting toolbar',
    toolbarBold: 'B',
    toolbarItalic: 'I',
    toolbarStrike: 'S',
    toolbarHeading1: 'H1',
    toolbarHeading2: 'H2',
    toolbarHeading3: 'H3',
    toolbarQuote: 'Quote',
    toolbarCode: 'Code',
    toolbarRule: '—',
    insertImage: 'Image',
    toolbarBulletList: '• List',
    toolbarOrderedList: '1. List',
    titleInputLabel: 'Note title',
    importDocument: 'Import document',
    importAsNoteContent: 'Import as note content',
    importAsEmbed: 'Embed document in note',
    importReplaceContent: 'Replace note content',
    importAppendContent: 'Append to note',
    importProcessing: 'Processing document…',
    importErrorSize: 'File exceeds the size limit.',
    importErrorType: 'Unsupported file type.',
    importEmbedErrorSize: 'Embedded files must be under 5 MB.',
    imageErrorSize: 'Image exceeds the 5 MB size limit.',
    imageErrorFormat: 'Unsupported image format. Use JPEG, PNG, WebP, or GIF.',
    exportAsPdf: 'Export as PDF',
    exportAsDocx: 'Export as Word document',
    embedPageOf: (current: number, total: number) =>
      `Page ${current} of ${total}`,
    embedPrev: 'Previous page',
    embedNext: 'Next page',
  },
  settings: {
    heading: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    language: 'Language',
    languageBritishEnglish: 'British English',
    llm: 'Language model',
    llmProvider: 'Provider',
    llmApiKey: 'API key',
    llmBaseUrl: 'Base URL',
    llmModel: 'Model',
    llmProviderGemini: 'Google Gemini',
    llmProviderOpenAI: 'OpenAI-compatible',
    llmProviderOllama: 'Ollama (local)',
    testConnection: 'Test connection',
    testConnectionSuccess: 'Connected successfully.',
    testConnectionFail: 'Connection failed.',
    llmNotConfigured: 'LLM is not configured.',
    llmNotConfiguredHint:
      'Configure an LLM provider in Settings to use this feature.',
    goToSettings: 'Go to settings',
    modelPlaceholderGemini: 'e.g. gemini-2.0-flash-lite',
    modelPlaceholderOpenAI: 'e.g. gpt-4o-mini',
    modelPlaceholderOllama: 'e.g. llama3',
    showApiKey: 'Show',
    hideApiKey: 'Hide',
    dataManagement: 'Data',
    exportData: 'Export data',
    importData: 'Import data',
    importConfirm:
      'Importing will overwrite any existing records with matching IDs. This cannot be undone.',
    importSuccess: (n: number) => `Imported ${n} records.`,
    importError: 'Import failed. The file may be invalid or corrupted.',
    dangerZone: 'Danger zone',
    deleteAllData: 'Delete all data',
    deleteAllDataConfirm:
      'This will permanently delete all decks, cards, and notes. This cannot be undone.',
    deleteAllTypingPrompt: 'Type "delete" to confirm:',
    deleteAllConfirmWord: 'delete',
  },
  cards: {
    loading: 'Loading cards...',
    errorLoad: 'Could not load cards.',
    empty: 'No cards in this deck yet.',
    addCard: 'Add card',
    editCard: 'Edit card',
    deleteCard: 'Delete card',
    deleteConfirm: 'Delete this card? This cannot be undone.',
    typeSelectorLabel: 'Card type',
    typeBasic: 'Basic',
    typeCloze: 'Cloze',
    frontLabel: 'Front',
    backLabel: 'Back',
    clozeLabel: 'Cloze text',
    front: 'Front',
    back: 'Back',
    clozeText: 'Cloze text',
    clozeHint:
      'Use {{c1::answer}} syntax. Multiple deletions: {{c1::first}}, {{c2::second}}.',
    clozeSyntaxHint:
      'Use {{c1::answer}} to mark deletions. Add a hint with {{c1::answer::hint}}.',
    clozeInvalid: (msg: string) => `Invalid cloze syntax: ${msg}`,
    clozeInvalidShort: 'No valid cloze deletions found.',
    previewLabel: 'Preview',
    preview: 'Preview',
    saveCard: 'Save card',
    frontRequired: 'Front is required.',
    backRequired: 'Back is required.',
    clozeRequired: 'Cloze text is required.',
    cardCount: (n: number) => `${n} card${n === 1 ? '' : 's'}`,
    dueCount: (n: number) => `${n} due`,
    nextDue: (label: string) => `Due ${label}`,
    neverReviewed: 'Not yet reviewed',
    typeImageOcclusion: 'Image occlusion',
    imageUploadPrompt: 'Click to upload or drag an image here.',
    imageUploadFormats:
      'Accepted formats: JPEG, PNG, WebP, GIF. Maximum size: 2 MB.',
    imageUploadErrorSize: 'Image exceeds the 2 MB size limit.',
    imageUploadErrorFormat: 'Unsupported file format.',
    imageReplaceButton: 'Replace image',
    occlusionDrawMode: 'Draw',
    occlusionSelectMode: 'Select',
    occlusionLabelPrompt: 'Label for this region:',
    occlusionLabelConfirm: 'Add',
    occlusionLabelCancel: 'Cancel',
    occlusionNoRegions: 'Draw at least one region before saving.',
    occlusionRegionCount: (n: number) => `${n} region${n === 1 ? '' : 's'}`,
    occlusionDeleteHint: 'Press Delete to remove the selected region.',
    tags: 'Tags',
    addTag: 'Add tag',
    linkedNotes: 'Linked notes',
    addLink: 'Add link',
    noLinkedNotes: 'No linked notes.',
    unlink: 'Unlink',
    chooseNote: 'Choose a note',
    noTags: '',
    tagPlaceholder: 'Add a tag\u2026',
  },
  tags: {
    heading: 'Tags',
    deleteTag: 'Delete tag',
    deleteTagConfirm: (name: string) =>
      `Delete the tag "${name}"? It will be removed from all cards.`,
    usageCount: (n: number) => `${n} card${n === 1 ? '' : 's'}`,
    clearFilters: 'Clear filters',
    filteringBy: (n: number) => `Filtering by ${n} tag${n === 1 ? '' : 's'}`,
    noTagsOnDeck: '',
  },
  llm: {
    generateCards: 'Generate cards',
    generating: 'Generating…',
    generatedCardsPreview: 'Review generated cards',
    addSelected: 'Add selected cards',
    cardType: 'Card type',
    cardCount: 'Number of cards',
    targetDeck: 'Add to deck',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
    explain: 'Explain',
    explanation: 'Explanation',
    closeExplanation: 'Close',
    practiceTest: 'Practice test',
    practiceTestFormat: 'Format',
    multipleChoice: 'Multiple choice',
    shortAnswer: 'Short answer',
    questionCount: 'Number of questions',
    generateTest: 'Generate test',
    revealAnswer: 'Reveal answer',
    suggestAlternatives: 'Suggest alternatives',
    alternatives: 'Suggested alternatives',
    applyAlternative: 'Use this',
    summarise: 'Summarise',
    summariseBrief: 'Brief',
    summariseDetailed: 'Detailed',
    summariseResult: 'Summary',
    closeSummary: 'Close',
  },
  common: {
    loading: 'Loading...',
    error: 'Something went wrong.',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    // Defined — not yet rendered in current UI
    confirm: 'Confirm',
    // Defined — not yet rendered in current UI
    back: 'Back',
    close: 'Close',
    edit: 'Edit',
    rename: 'Rename',
    // Defined — not yet rendered in current UI
    search: 'Search',
    notFound: 'Page not found.',
    backToHome: 'Back to home',
    reload: 'Reload',
    noResults: 'No results.',
  },
} as const;
