export const UI = {
  nav: {
    home: 'Home',
    decks: 'Decks',
    review: 'Review',
    notes: 'Notes',
    settings: 'Settings',
  },
  home: {
    heading: 'Lacuna',
    dueToday: (n: number) => `${n} card${n === 1 ? '' : 's'} due today`,
    startReview: 'Start revision',
    noCardsDue: 'No cards due. Come back later, or add a new deck.',
  },
  decks: {
    heading: 'Decks',
    empty: 'No decks yet. Create one to get started.',
    createDeck: 'New deck',
    deleteDeck: 'Delete deck',
    renameDeck: 'Rename deck',
    examDate: 'Exam date',
    examDateSet: 'Exam date set',
    cardCount: (n: number) => `${n} card${n === 1 ? '' : 's'}`,
    dueCount: (n: number) => `${n} due`,
    nested: 'Sub-deck',
  },
  review: {
    heading: 'Review',
    flip: 'Show answer',
    again: 'Again',
    hard: 'Hard',
    good: 'Good',
    easy: 'Easy',
    sessionComplete: 'Revision complete.',
    cardsRemaining: (n: number) => `${n} card${n === 1 ? '' : 's'} remaining`,
    exitSession: 'End session',
    examModeActive: 'Exam mode active',
    examWarning: (count: number, date: string) =>
      `At your current revision pace, you can meaningfully cover approximately ${count} cards before your exam on ${date}.`,
  },
  notes: {
    heading: 'Notes',
    empty: 'No notes yet.',
    untitled: 'Untitled note',
    createNote: 'New note',
    deleteNote: 'Delete note',
    linkToDeck: 'Link to deck',
    generateCards: 'Generate cards',
  },
  settings: {
    heading: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    language: 'Language',
    llm: 'Language model',
    llmProvider: 'Provider',
    llmApiKey: 'API key',
    llmBaseUrl: 'Base URL',
    llmModel: 'Model',
    llmProviderGemini: 'Google Gemini',
    llmProviderOpenAI: 'OpenAI-compatible',
    llmProviderOllama: 'Ollama (local)',
    dataManagement: 'Data',
    exportData: 'Export data',
    importData: 'Import data',
    dangerZone: 'Danger zone',
    deleteAllData: 'Delete all data',
    deleteAllDataConfirm:
      'This will permanently delete all decks, cards, and notes. This cannot be undone.',
  },
  common: {
    loading: 'Loading...',
    error: 'Something went wrong.',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    back: 'Back',
    close: 'Close',
    edit: 'Edit',
    rename: 'Rename',
    search: 'Search',
    notFound: 'Not found.',
    noResults: 'No results.',
  },
} as const;
